[#14] [Feature] [Part 2] Implement home screen UI
nimblehq/flutter-ic-kaung-thieu pull request #56
Opened 2023-04-19 06:16 UTC by kaungkhantsoe

- Closes #14 
- [x] Add shimmer loading
- [x] Add home screen UI

## What happened 👀

Add Home screen UI.

## Insight 📝

- Implement a horizontal scroll view with paging.
- Show the header:
- Show the current date.
- Show the user's avatar.
- Show the background image view.
- Show the Page indicators.
- Show the Title label.
- Show the Description label.
- Show the button with the right chevron icon.

## Proof Of Work 📹

<img width="434" alt="Screenshot 2023-04-19 at 1 09 43 PM" src="https://user-images.githubusercontent.com/32578035/232983192-54929428-1a13-4d65-b294-e9373031044d.png">

2023-04-19 07:21 UTC, manh-t requested changes
Done my first round 🙏

2023-04-19 07:21 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +              padding: const EdgeInsets.fromLTRB(20, 60, 0, 0),
```suggestion
              padding: const EdgeInsets.only(left: 20, top: 60),
```
And we should extract the dimen to a variable instead of hardcoding here

2023-04-19 07:21 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +                    'Monday, JUNE 15',
although this is not the integration task, I still recommend creating a basic VM and get the date from VM (we can hardcode this value in VM for UI task, and replace it with the real value in integration task).

2023-04-19 07:21 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +                      fontSize: 13,
Can we extract font size value to a variable?

2023-04-19 07:21 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +                        fontSize: 34,
same here

2023-04-19 07:21 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +              padding: const EdgeInsets.fromLTRB(0, 79, 20, 0),
please apply the same above approach 😁

2023-04-19 07:21 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +                  size: const Size.fromRadius(18), // Image radius
Can we extract radius value to a variable?

2023-04-19 07:21 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +                  padding: const EdgeInsets.fromLTRB(20, 26, 20, 0),
please use `EdgeInsets.only` here

2023-04-20 10:13 UTC, manh-t requested changes

2023-04-20 10:13 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +              .toList(),
the current implementation doesn't follow reactive programming, so if the `surveys` value has been changed, the widget won't be rebuilt / updated correspondingly. Please  apply observable for the variable.

We have `LiveData`, or `Flow` in Android, while Flutter has `Stream` . [Ref](https://riverpod.dev/docs/providers/stream_provider)

2023-04-20 10:13 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +          visible: viewModel.profile != null,
Note that when updating `profile` data type to `Stream`, we should apply [Consumer](https://pub.dev/documentation/flutter_riverpod/latest/flutter_riverpod/Consumer-class.html) widget to get the `profile` value

2023-04-20 10:13 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +                  viewModel.surveys[_selectedPage].title,
please update `surveys` data type to `Stream` and get the value through Consumer. Apply the same approach to below variables from ViewModel too

2023-04-20 10:13 UTC, manh-t commented on lib/screens/home/home_view_model.dart
> +class HomeViewModel extends AutoDisposeAsyncNotifier {
```suggestion
class HomeViewModel extends AutoDisposeAsyncNotifier<void> {
```
If there is no specific data type, please use `void`

2023-04-20 10:13 UTC, manh-t commented on lib/screens/home/home_view_model.dart
> +  FutureOr<dynamic> build() {
```suggestion
  FutureOr<void> build() {
```

2023-04-20 10:13 UTC, manh-t commented on lib/screens/home/home_view_model.dart
> +    state = AsyncValue.data(_currentDate);
It seems you misunderstand the `state` purpose. Calling it here is a trick to rebuilding the widget unnecessarily. If we change `currentDate` data type to `Stream`, we don't need to call the `state` here.

2023-04-20 10:13 UTC, manh-t commented on lib/screens/home/home_view_model.dart
> +      state = AsyncValue.data(_surveys);
same here

2023-04-20 10:13 UTC, manh-t commented on lib/screens/home/home_view_model.dart
> +      state = AsyncValue.data(_profile);
and here

2023-04-21 08:08 UTC, manh-t reviewed
```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 107 pos 12: '_positions.isNotEmpty'

When the exception was thrown, this was the stack:
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:107:12)
#3      _PageViewDotIndicatorState._getOffsetForCurrentPosition (package:page_view_dot_indicator/src/indicator.dart:165:27)
#4      _PageViewDotIndicatorState.scrollToCurrentPosition (package:page_view_dot_indicator/src/indicator.dart:102:26)
#5      _PageViewDotIndicatorState.initState.<anonymous closure> (package:page_view_dot_indicator/src/indicator.dart:90:7)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:9)
#8      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:881:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)
```
I'm facing an error with `PageViewDotIndicator`. Can you help check? 🙏

2023-04-21 08:08 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +                ),
same here, please create Consumer widget for it

2023-04-21 08:55 UTC, kaungkhantsoe commented on lib/screens/home/home_screen.dart
> +    );
@manh-t I tried using `Consumer` before and I got the following error. That's why I used `Visibility` instead. I tried to solve the error but I don't know what it is talking about 😅 .
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while rebuilding dirty elements:
Got a stack frame from package:stack_trace, where a vm or web frame was expected. This can happen if FlutterError.demangleStackTrace was not set in an environment that propagates non-standard stack traces to the framework, such as during tests.
'package:flutter/src/foundation/stack_frame.dart':
Failed assertion: line 192 pos 7: 'line != '===== asynchronous gap ===========================''

The relevant error-causing widget was: 
  Consumer Consumer:file:///Users/kaungkhantsoe/Documents/Work/Nimble/flutter-ic-kaung-thieu/lib/screens/home/home_screen.dart:55:16
When the exception was thrown, this was the stack: 
#2      StackFrame.fromStackTraceLine (package:flutter/src/foundation/stack_frame.dart:192:7)
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:393:20)
#4      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:871:20)
#5      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#7      new List.of (dart:core-patch/array_patch.dart:52:28)
#8      Iterable.toList (dart:core/iterable.dart:470:12)
#9      StackFrame.fromStackString (package:flutter/src/foundation/stack_frame.dart:93:10)
#10     FlutterError.defaultStackFilter (package:flutter/src/foundation/assertions.dart:1077:54)
#11     DiagnosticsStackTrace._applyStackFilter (package:flutter/src/foundation/assertions.dart:1273:43)
#12     new DiagnosticsStackTrace (package:flutter/src/foundation/assertions.dart:1249:17)
#13     FlutterErrorDetails.debugFillProperties (package:flutter/src/foundation/assertions.dart:732:22)
#14     DiagnosticableNode.builder.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:2958:17)
#15     DiagnosticableNode.builder (package:flutter/src/foundation/diagnostics.dart:2961:8)
#16     _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1294:56)
#17     DiagnosticableNode.emptyBodyDescription (package:flutter/src/foundation/diagnostics.dart:2972:77)
#18     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1650:13)
#19     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1679:6)
#20     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1639:18)
#21     WidgetInspectorService._reportStructuredError (package:flutter/src/widgets/widget_inspector.dart:934:44)
#22     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1189:14)
#23     _reportException (package:flutter/src/widgets/framework.dart:6570:16)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:9)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#27     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#28     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#29     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#30     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#31     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#32     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#33     _invoke (dart:ui/hooks.dart:145:13)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#35     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
The element being rebuilt at the time was index 1 of 3: Consumer
  dependencies: [UncontrolledProviderScope]
  state: _ConsumerState#1dc66
```

2023-04-21 09:04 UTC, kaungkhantsoe commented on lib/screens/home/home_screen.dart
> +        ),
@manh-t quick question. Should I use `ref.watch` or `widgetRef.watch` here?

2023-04-21 09:12 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +        ),
@kaungkhantsoe oh my bad, it should be `widgetRef` 😁 Updated

2023-04-24 03:15 UTC, manh-t reviewed
The structure is better now. Just some minor things and it's good to go 🚀

2023-04-24 03:15 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +      body: Builder(builder: (BuildContext context) {
I think we don't need to use `Builder` widget here 🙏

2023-04-24 03:15 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +        ),
we are using `ref` for most widgets here. How about wrapping the `Consumer` widget to the parent widget `Align`? 😄

2023-04-24 03:15 UTC, manh-t commented on pubspec.yaml
> +  page_view_dot_indicator: ^1.1.0
according to the [package's instruction](https://pub.dev/packages/page_view_dot_indicator), we should use `2.0.0` for Flutter 3. Reference thread: https://nimble-co.slack.com/archives/C04TSH99BRN/p1682305304711289

2023-04-24 10:38 UTC, manh-t reviewed
we need to replace `ref` with `widgetRef`. Rest LGTM

2023-04-24 10:38 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +                ref.read(homeViewModelProvider.notifier).getSurveyList();
```suggestion
                widgetRef.read(homeViewModelProvider.notifier).getSurveyList();
```

2023-04-24 10:38 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +                        '',
```suggestion
                    widgetRef
                            .watch(_surveysStreamProvider)
                            .value?[_selectedPage]
                            .title ??
                        '',
```

2023-04-24 10:38 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +                              '',
```suggestion
                          widgetRef
                                  .watch(_surveysStreamProvider)
                                  .value?[_selectedPage]
                                  .description ??
                              '',
```

2023-04-25 03:10 UTC, manh-t reviewed
The code structure is better now, but I'm facing this error with the latest change. Can you check?
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Consumer(dependencies: [UncontrolledProviderScope],
state: _ConsumerState#86083):
Got a stack frame from package:stack_trace, where a vm or web frame was expected. This can happen if
FlutterError.demangleStackTrace was not set in an environment that propagates non-standard stack
traces to the framework, such as during tests.
'package:flutter/src/foundation/stack_frame.dart':
Failed assertion: line 192 pos 7: 'line != '===== asynchronous gap ===========================''

The relevant error-causing widget was:
  Consumer
  Consumer:file:///Users/tranmanh/Desktop/nimble/ic/flutter-ic-kaung-thieu/lib/screens/home/home_screen.dart:66:13

When the exception was thrown, this was the stack:
#2      StackFrame.fromStackTraceLine (package:flutter/src/foundation/stack_frame.dart:192:7)
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#4      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:869:20)
#5      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#7      new List.of (dart:core-patch/array_patch.dart:51:28)
#8      Iterable.toList (dart:core/iterable.dart:470:12)
#9      StackFrame.fromStackString (package:flutter/src/foundation/stack_frame.dart:93:10)
#10     FlutterError.defaultStackFilter (package:flutter/src/foundation/assertions.dart:1072:54)
#11     DiagnosticsStackTrace._applyStackFilter (package:flutter/src/foundation/assertions.dart:1268:43)
#12     new DiagnosticsStackTrace (package:flutter/src/foundation/assertions.dart:1244:17)
#13     FlutterErrorDetails.debugFillProperties (package:flutter/src/foundation/assertions.dart:730:22)
#14     DiagnosticableNode.builder.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:2940:17)
#15     DiagnosticableNode.builder (package:flutter/src/foundation/diagnostics.dart:2943:8)
#16     _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1289:56)
#17     DiagnosticableNode.emptyBodyDescription (package:flutter/src/foundation/diagnostics.dart:2954:77)
#18     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:13)
#19     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1661:6)
#20     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1606:18)
#21     WidgetInspectorService._reportStructuredError (package:flutter/src/widgets/widget_inspector.dart:937:44)
#22     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1184:14)
#23     _debugReportException (package:flutter/src/widgets/framework.dart:6493:16)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4887:9)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859:5)
#28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041:11)
#29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3586:20)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#35     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#36     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#37     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#38     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#39     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#40     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#41     _invoke (dart:ui/hooks.dart:148:13)
#42     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#43     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 2 frames from class _AssertionError)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4606 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
```

2023-04-26 07:10 UTC, manh-t reviewed
Revamp the widget tree and minor fixes

2023-04-26 07:10 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +              });
```suggestion
              },
          );
```
Please don't forget to put trailing comma at the end 😁

2023-04-26 07:10 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +      required VoidCallback onLoadMore}) {
```suggestion
      required VoidCallback onLoadMore,
  }) {
```

2023-04-26 07:10 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +      children: [
For a long widget like this, I prefer to extract their children into small methods, such as `_buildHeader`, `_buildUserAvatar`, `_buildSurveyContent`, `_buildLoadingIndicator`, etc. for more readability

2023-04-26 07:10 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +          ),
so `_buildHeader` can goes here

2023-04-26 07:10 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +          ),
`_buildUserAvatar` for this? 😃

2023-04-26 07:10 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +          ),
`_buildSurveyContent` here? 💡

2023-04-26 07:10 UTC, manh-t commented on lib/screens/home/home_screen.dart
> +          ),
`_buildLoadingIndicator` here 🦅

2023-04-26 07:10 UTC, manh-t commented on lib/screens/home/home_view_model.dart
> +  Stream<bool> get isLoadMore => _isLoadMore.stream;
```suggestion
  final _profile = StreamController<ProfileModel>();
  Stream<ProfileModel> get profile => _profile.stream;

  final _currentDate = StreamController<String>();
  Stream<String> get currentDate => _currentDate.stream;

  final _isError = StreamController<String>();
  Stream<String> get isError => _isError.stream;

  final _isLoadMore = StreamController<bool>();
  Stream<bool> get isLoadMore => _isLoadMore.stream;
```
The Stream variables are being listened once, so we don't need `broadcast`

2023-04-26 07:10 UTC, manh-t commented on lib/screens/home/home_view_model.dart
> +  Stream<bool> get shouldShowShimmer => _shouldShowShimmer.stream;
@kaungkhantsoe you forget adding `dispose` for stream variables. Please add it 🙋

2023-04-26 09:33 UTC, kaungkhantsoe commented on lib/screens/home/home_view_model.dart
> +  Stream<bool> get shouldShowShimmer => _shouldShowShimmer.stream;
@manh-t Did you mean I have to close private stream variables like `_shouldShowShimmer`? Because I am getting other `Streams` with `.autoDispose` option in `HomeScreen`. If so I can make a function inside ViewModel like `dispose` and call it from HomeScreen's `dispose` since my viewmodel extends `AutoDisposeAsyncNotifier` and it doesn't have `dispose` override method.

2023-04-26 09:50 UTC, manh-t commented on lib/screens/home/home_view_model.dart
> +  Stream<bool> get shouldShowShimmer => _shouldShowShimmer.stream;
@kaungkhantsoe The `StreamProvider` from riverpod will be disposed automatically if we use `.autoDispose`. But for the `StreamController` variables inside the ViewModel, they do not close automatically. So we need to add `streamController.close()` on the `onDispose` method of `ref` in VM. For example:
![image](https://user-images.githubusercontent.com/60863885/234538777-299ac6df-8341-456e-9c7f-8d793dbbe178.png)

Here is the example from [the resource](https://pub.dev/documentation/riverpod/latest/riverpod/AutoDisposeProvider-class.html): 😄 
![image](https://user-images.githubusercontent.com/60863885/234539057-916555aa-6522-4e00-a0ed-9a317ad6f73e.png)

2023-04-26 10:45 UTC, manh-t commented on lib/screens/home/home_view_model.dart
> +  }
@kaungkhantsoe we only need to close Stream variables once in `ref.onDispose` 😂 `disposeStreams` is redundant

2023-04-27 03:21 UTC, manh-t approved these changes

2023-04-28 02:10 UTC, Thieurom approved these changes
🚀

2023-04-28 03:00 UTC, merged