[#10] [Feature] Integrate user login. Add error response for custom error message.
nimblehq/flutter-ic-kaung-thieu pull request #63
Opened 2023-05-03 10:29 UTC by kaungkhantsoe

https://github.com/nimblehq/flutter-templates/issues/??

## What happened 👀

Describe the big picture of your changes here to communicate to the team why we should accept this pull request.

## Insight 📝

Describe in details how to test the changes, which solution you tried but did not go with, referenced documentation is
welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, gif, etc.

<img src="URL_GOES_HERE" width=200 />

2023-05-10 04:07 UTC, manh-t commented
I face an error with Login Form. Steps:
- Press Login button at the first time.
- Then enter any email and password.
- Press Login button again.
- Observe that there is a red square box displayed.

Please help me check. I think this error is because the wrong usage `ref.read` or `ref.watch` in your `_emailValidator` and `_passwordValidator` methods.

https://github.com/nimblehq/flutter-ic-kaung-thieu/assets/60863885/abd03334-c95f-4291-b236-b4a64fb6a0f8

2023-05-10 06:47 UTC, kaungkhantsoe commented on pubspec.yaml
> +  collection: ^1.17.0
@manh-t I tried using `firstOrNull` from `collection` before adding this and I couldn't. That's why. Any idea why I couldn't use `firstOrNull` before?

2023-05-10 06:55 UTC, kaungkhantsoe commented on lib/screens/login/login_form.dart
> +                    onPressed: () => Navigator.pop(context),
`context.pop` doesn't work @manh-t . It doesn't close the pop-up. 😢

2023-05-10 07:19 UTC, manh-t commented on pubspec.yaml
> +  collection: ^1.17.0
@kaungkhantsoe maybe the IDE didn't suggest importing `collection` package, we have to import it manually

2023-05-10 07:38 UTC, manh-t commented on lib/screens/login/login_form.dart
> +                    onPressed: () => Navigator.pop(context),
ah I see, this is the dialog. Let's keep it 👌

2023-05-11 02:50 UTC, manh-t commented on pubspec.yaml
> +  collection: ^1.17.0
@kaungkhantsoe it's not the error, it's the warning and we are fine with it. After removing `collection` from pubspec, please fetch the pubpsec file again.

2023-05-11 03:42 UTC, manh-t requested changes
Currently the Login Form and its validation methods are complicated. I suggest following [the best practice](https://docs.flutter.dev/cookbook/forms/validation) from Flutter 🙋

2023-05-11 03:42 UTC, manh-t commented on lib/screens/login/login_form.dart
> +      ],
@kaungkhantsoe I realize ... we should follow the [best practices](https://docs.flutter.dev/cookbook/forms/validation) from Flutter to create a Form 😅 Currently you are creating multiple work around for the form validator. Why don't we follow Flutter instruction to create a Form as the simplest way? 🤤 
I have modified the code and it works well. Here is the example:
```suggestion
    return Form(
      key: _formKey,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          TextFormField(
            keyboardType: TextInputType.emailAddress,
            autocorrect: false,
            decoration: FormFieldDecoration(
              hint: _localizations.emailInputHint,
              hintTextStyle: _textTheme.bodyLarge,
            ),
            style: _textTheme.bodyLarge,
            controller: emailController,
            validator: (value) => ref
                .read(loginViewModelProvider.notifier)
                .checkEmail(value, _localizations.invalidEmailError),
          ),
          const SizedBox(
            height: fieldSpacing,
          ),
          TextFormField(
            autocorrect: false,
            obscureText: true,
            decoration: FormFieldDecoration(
              hint: _localizations.passwordInputHint,
              hintTextStyle: _textTheme.bodyLarge,
            ),
            style: _textTheme.bodyLarge,
            controller: passwordController,
            validator: (value) => ref
                .read(loginViewModelProvider.notifier)
                .checkPassword(value, _localizations.invalidPasswordError),
          ),
          const SizedBox(
            height: fieldSpacing,
          ),
          SizedBox(
            height: 56,
            width: double.infinity,
            child: _loginButton,
          )
        ],
      ),
```

2023-05-11 03:42 UTC, manh-t commented on lib/screens/login/login_form.dart
> +      ref.read(loginViewModelProvider.notifier).login();
Then we don't need the email or password stream variable here. Just check it by using `_formKey`:
```suggestion
    KeyboardManager.dismiss(context);
    if (_formKey.currentState!.validate()) {
      ref.read(loginViewModelProvider.notifier).login();
```

2023-05-11 03:42 UTC, manh-t commented on lib/screens/login/login_form.dart
> +  }
we can get rid of unused stuff here by following the best practice's approach

2023-05-11 03:42 UTC, manh-t commented on lib/screens/login/login_form.dart
> +    });
we don't need the listeners too

2023-05-11 03:42 UTC, manh-t commented on lib/screens/login/login_view_model.dart
> +  }
modify the methods to return the error message if the value is invalid.
```suggestion
  String? checkEmail(String? email, String errorMessage) {
    _email = email ?? '';
    if (email == null || email.isEmpty || !email.contains('@')) {
      return errorMessage;
    }
    return null;
  }

  String? checkPassword(String? password, String errorMessage) {
    _password = password ?? '';
    if (password == null || password.isEmpty || password.length < 8) {
      return errorMessage;
    }
    return null;
  }
```

2023-05-11 03:42 UTC, manh-t commented on lib/screens/login/login_view_model.dart
> +  Stream<bool> get isValidPassword => _isValidPassword.stream;
then remove these variables

2023-05-11 07:17 UTC, kaungkhantsoe commented on pubspec.yaml
> +  collection: ^1.17.0
![Screenshot 2023-05-11 at 2 16 13 PM (2)](https://github.com/nimblehq/flutter-ic-kaung-thieu/assets/32578035/97c57ce5-93e5-4647-8f82-3b11fc38d2c5)

@manh-t I did fetch the pubspec again and also run `flutter analyze .`. It failed the check.

2023-05-11 08:06 UTC, manh-t commented on pubspec.yaml
> +  collection: ^1.17.0
@kaungkhantsoe we can pass the Flutter lint easily fix it by adding a comment before:
```
// ignore: depend_on_referenced_packages
import 'package:collection/collection.dart';
```

2023-05-11 10:48 UTC, manh-t approved these changes
LGTM now 🚀

2023-05-12 04:01 UTC, Thieurom approved these changes
You're really fast, @kaungkhantsoe!
And thank you for helping taking over this task 🙏

2023-05-12 04:02 UTC, merged