[#13] [Integrate] As a logged-in user, I can see the Home screen when I relaunch the app
nimblehq/flutter-ic-kaung-thieu pull request #66
Opened 2023-05-11 10:39 UTC by kaungkhantsoe

- Closes #13 

## What happened 👀

- If the user has previously logged in when relaunching the app, the user doesn't have to log in but goes straight to the Home screen.
- Unit tests are added and passed.

## Insight 📝

If the user is already logged in, there would be `accessToken` cached inside the app. I have checked if there is `accessToken` or not to check whether the user is already logged in.

## Proof Of Work 📹

https://github.com/nimblehq/flutter-ic-kaung-thieu/assets/32578035/cf1f1837-8efc-427c-b0d1-063d6a3a4760

2023-05-12 03:25 UTC, manh-t commented
@kaungkhantsoe conflicts 🙋

2023-05-15 04:03 UTC, manh-t requested changes

2023-05-15 04:03 UTC, manh-t commented on lib/screens/splash/splash.dart
> +    final sharedPreference = ref.watch(sharedPreferenceProvider);
@kaungkhantsoe please create the ViewModel and a use case to fetch the login status instead 🙏 We don't do it in UI

2023-05-16 03:30 UTC, manh-t approved these changes
LGTM now

2023-05-17 08:22 UTC, Thieurom approved these changes

2023-05-18 02:23 UTC, merged