[#27] backend implementation for submit survey
nimblehq/flutter-ic-kaung-thieu pull request #84
Opened 2023-05-19 04:56 UTC by kaungkhantsoe

- Closes #27 

## What happened 👀

The user can submit their answers to the survey questions.

## Insight 📝

- Add logic in repository
- Add usecase
- Add unit tests

## Proof Of Work 📹

![Screenshot 2023-05-19 at 11 48 51 AM (2)](https://github.com/nimblehq/flutter-ic-kaung-thieu/assets/32578035/6bd536c9-bfe6-458c-989b-7c3fd1723be9)
![Screenshot 2023-05-19 at 11 45 24 AM (2)](https://github.com/nimblehq/flutter-ic-kaung-thieu/assets/32578035/77699ba1-0960-4c6c-b41c-a68e05ec4f82)

2023-05-19 08:29 UTC, manh-t reviewed
Because we are submitting the questions for a survey, it should be singular `submitSurvey` 😄

2023-05-19 08:29 UTC, manh-t commented on lib/api/api_service.dart
> +  Future<void> submitSurveys(@Body() SubmitSurveysRequest submitSurveysRequest);
```suggestion
  Future<void> submitSurvey(@Body() SubmitSurveyRequest submitSurveyRequest);
```

2023-05-19 08:29 UTC, manh-t commented on lib/api/repository/survey_repository.dart
> +  Future<void> submitSurveys(SubmitSurveysRequest submitSurveyRequest);
```suggestion
  Future<void> submitSurvey(SubmitSurveyRequest submitSurveyRequest);
```

2023-05-19 08:29 UTC, manh-t commented on lib/model/request/submit_surveys_request.dart
> +class SubmitSurveysRequest {
```suggestion
class SubmitSurveyRequest {
```

2023-05-22 03:14 UTC, manh-t requested changes
there are still some places which are having `s` in `SubmitSurveys`. Please update them 🙏

2023-05-22 03:14 UTC, manh-t commented on lib/api/api_service.dart
> +  Future<void> submitSurvey(@Body() SubmitSurveyRequest submitSurveysRequest);
```suggestion
  Future<void> submitSurvey(@Body() SubmitSurveyRequest submitSurveyRequest);
```

2023-05-22 03:14 UTC, manh-t commented on lib/model/request/submit_surveys_request.dart
@kaungkhantsoe please rename the file as well

2023-05-22 03:14 UTC, manh-t commented on lib/model/request/submit_surveys_request.dart
> +part 'submit_surveys_request.g.dart';
```suggestion
part 'submit_survey_request.g.dart';
```

2023-05-22 03:14 UTC, manh-t commented on lib/usecases/submit_surveys_use_case.dart
please rename the file to `submit_survey_use_case.dart`

2023-05-22 03:14 UTC, manh-t commented on lib/usecases/submit_surveys_use_case.dart
> +  SubmitSurveysUseCase(this._surveyRepository);
update the class's name too

2023-05-22 03:14 UTC, manh-t commented on test/usecases/submit_surveys_use_case_test.dart
> +            await submitSurveysUseCase.call(MockUtil.submitSurveysRequest);
```suggestion
            await submitSurveysUseCase.call(MockUtil.submitSurveyRequest);
```

2023-05-22 03:14 UTC, manh-t commented on test/mocks/mock_util.dart
> +  static SubmitSurveyRequest submitSurveysRequest = SubmitSurveyRequest(
```suggestion
  static SubmitSurveyRequest submitSurveyRequest = SubmitSurveyRequest(
```

2023-05-22 03:14 UTC, manh-t commented on test/usecases/submit_surveys_use_case_test.dart
> +        'When calling submitSurveys with SubmitSurveysRequest successfully, it emits success',
```suggestion
        'When calling submitSurvey with SubmitSurveyRequest successfully, it emits success',
```

2023-05-22 03:14 UTC, manh-t commented on test/usecases/submit_surveys_use_case_test.dart
> +      'When calling submitSurveys with SubmitSurveysRequest unsuccessfully, it emits failed',
```suggestion
      'When calling submitSurvey with SubmitSurveyRequest unsuccessfully, it emits failed',
```

2023-05-22 03:14 UTC, manh-t commented on test/usecases/submit_surveys_use_case_test.dart
> +        submitSurveysUseCase = SubmitSurveysUseCase(mockSurveyRepository));
```suggestion
        submitSurveyUseCase = SubmitSurveyUseCase(mockSurveyRepository));
```

2023-05-22 08:41 UTC, manh-t approved these changes

2023-05-22 09:22 UTC, ducbm051291 approved these changes

2023-05-22 09:35 UTC, merged