[#23] [UI] As a logged-in user, I can see the NPS Survey Question
nimblehq/flutter-ic-kaung-thieu pull request #89
Opened 2023-05-21 11:10 UTC by kaungkhantsoe

- Closes #23 

## What happened 👀

The user can see the question and the available answers and select their answer.

## Insight 📝

- Show the question.
- Show the answers as a score.
- User can select their score. When the user selects one score, the scores behind the selected score are selected too.

## Proof Of Work 📹

https://github.com/nimblehq/flutter-ic-kaung-thieu/assets/32578035/2448af95-8ad8-4125-b2a1-352ff2fefc72

2023-05-22 10:01 UTC, ducbm051291 commented on lib/screens/detail/nps_answer.dart
> +                          widget.answers.length / 2.round()) {
Please check this 
```suggestion
                          (widget.answers.length / 2).round()) {
```

2023-05-22 10:13 UTC, ducbm051291 commented on lib/screens/detail/nps_answer.dart
> +                          widget.answers.length / 2.round()) {
Oops, this one too :D

2023-05-22 10:14 UTC, ducbm051291 commented on lib/screens/detail/nps_answer.dart
> +    return Column(
I think we should make a flag here and use it for below code? 

```suggestion
    final isNotAtAllLikely = (_selectedIndex != null &&
                      (_selectedIndex ?? 0) <
                          widget.answers.length / 2.round())
```

2023-05-23 04:09 UTC, ducbm051291 commented
Please check my comment and resolve conflict ;)

2023-05-23 04:21 UTC, kaungkhantsoe commented on lib/screens/detail/nps_answer.dart
> +    return Column(
@ducbm051291 They are not duplicated. They both have to check whether the `_selectedIndex` is `null` or not at first and the rest is their condition. IMO I don't think making a flag here could a lot of difference here. 🙏

2023-05-23 04:36 UTC, ducbm051291 approved these changes

2023-05-23 07:22 UTC, manh-t requested changes

2023-05-23 07:22 UTC, manh-t commented on lib/screens/detail/nps_answer.dart
> +                }()),
@kaungkhantsoe sorry but we don't allow writing an anonymous function directly to get a value like this. It's not friendly and makes us confused when looking at the code.

Normally we have two approaches:
- Extract to a function such as `getNpsTextColor`.
- Apply condition like this:
```suggestion
                style: _textTheme.labelMedium?.copyWith(
                  color: (_selectedIndex != null &&
                          (_selectedIndex ?? 0) <
                              widget.answers.length / 2.round())
                      ? Colors.white
                      : Colors.white.withOpacity(0.5),
                ),
```

2023-05-23 07:22 UTC, manh-t commented on lib/screens/detail/nps_answer.dart
> +                }()),
same here, please refactor it

2023-05-23 07:22 UTC, manh-t commented on lib/screens/detail/nps_answer.dart
> +          }(),
and here

2023-05-23 07:22 UTC, manh-t commented on lib/screens/detail/nps_answer.dart
> +            }(),
here too

2023-05-23 08:54 UTC, kaungkhantsoe commented
@manh-t  Fixed all in https://github.com/nimblehq/flutter-ic-kaung-thieu/pull/89/commits/0e8cdd84aab9fad10397e36dfb2e2e7b2ad17708

2023-05-24 02:52 UTC, manh-t approved these changes

2023-05-24 05:51 UTC, merged